sonar.projectKey=shivams9575_British-Spoken-Time-Project
sonar.organization=shivams9575
sonar.host.url=https://sonarcloud.io
sonar.language=java
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java

# Reports
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Optional exclusions
sonar.exclusions=**/test/**